Repository U37-Solutions/drmp-admin-frontend, pull requests merged in 2025-06, with the labels that each got.

#2 feat: connect antd, init light&dark themes
  .gitignore
  package-lock.json
  package.json
  src/app/components/Header/Header.tsx
  src/app/components/MainLayout.tsx
  src/app/components/Sidebar/Sidebar.module.scss
  src/app/components/Sidebar/Sidebar.tsx
  src/app/components/index.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/shared/ui/themes/dark.ts
  src/shared/ui/themes/index.ts
  src/shared/ui/themes/light.ts
Labels: feature

#5 fix: update eslint rules and fix lint problems
  eslint.config.mjs
  src/app/components/Sidebar/Sidebar.tsx
Labels: bug

#7 ci: add deployment
  .github/workflows/deploy.yml
  Dockerfile
  next.config.ts
  public/favicon.ico
Labels: chore

#6 feat: implement authentication
  .env.example
  src/app/(app)/layout.tsx
  src/app/(app)/loading.tsx
  src/app/(app)/profile/page.tsx
  src/app/(app)/users/page.tsx
  src/app/(auth)/layout.module.scss
  src/app/(auth)/layout.tsx
  src/app/(auth)/loading.tsx
  src/app/(auth)/login/page.module.scss
  src/app/(auth)/login/page.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/refresh-session/route.ts
  src/app/components/Header/Header.tsx
  src/app/components/MainLayout.tsx
  src/app/components/Sidebar/Sidebar.tsx
  src/app/components/TopMenu/TopMenu.tsx
  src/app/components/index.ts
  src/app/layout.module.scss
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/features/session/api.ts
  src/features/session/store.ts
  src/features/session/types.ts
  src/lib/api-client.ts
  src/lib/providers/session-provider.tsx
  src/middleware.ts
  src/shared/ui/styles/base/_index.scss
  src/shared/ui/styles/global.scss
  src/shared/ui/styles/utils/_index.scss
Labels: feature

#10 refactor: update eslint rules and fix lint problems
  .env.example
  README.md
  eslint.config.js
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/TopMenu.tsx
  src/features/auth/AuthProvider.tsx
  src/features/auth/components/LoginForm/LoginForm.tsx
  src/features/auth/types.ts
  src/main.tsx
  src/routes/_authorized/route.tsx
  src/routes/_unauthorized/login.tsx
  src/services/api-client.ts
  src/shared/providers/AppProvider.tsx
  src/shared/ui/themes/dark.ts
  src/shared/ui/themes/light.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.mts
Labels: bug

#11 ci: update Dockerfile for React
  Dockerfile
Labels: chore

#13 ci: fix Dockerfile to use env
  .github/workflows/deploy.yml
  Dockerfile
Labels: chore

#12 feat: create users page, session context, session store
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/TopMenu.tsx
  src/features/auth/AuthProvider.tsx
  src/features/session/store.ts
  src/features/users/api.ts
  src/features/users/columns.ts
  src/features/users/components/UsersTable.tsx
  src/features/users/types.ts
  src/main.tsx
  src/routeTree.gen.ts
  src/routes/__root.tsx
  src/routes/_authorized/_admin/route.tsx
  src/routes/_authorized/_admin/users.tsx
  src/routes/_authorized/route.tsx
  src/routes/_authorized/users.tsx
  src/services/api-client.ts
  src/services/filter-table-data.ts
  src/services/sort-columns.ts
  src/shared/hooks/index.ts
  src/shared/hooks/useTableState.ts
  src/shared/providers/AppProvider.tsx
  src/shared/providers/ThemeProvider.tsx
  src/shared/providers/UserRoleProvider.tsx
Labels: feature

#14 feat: create reset password flow, add responsiveness
  src/features/auth/api.ts
  src/features/auth/components/ForgotPasswordForm/ForgotPasswordForm.tsx
  src/features/auth/components/LoginForm/LoginForm.module.scss
  src/features/auth/components/ResetPasswordForm/ResetPasswordForm.tsx
  src/features/auth/validation.ts
  src/features/users/components/UsersTable.tsx
  src/index.css
  src/main.tsx
  src/routeTree.gen.ts
  src/routes/_authorized/route.tsx
  src/routes/_unauthorized/check-email.tsx
  src/routes/_unauthorized/forgot-password.tsx
  src/routes/_unauthorized/index.module.scss
  src/routes/_unauthorized/login.tsx
  src/routes/_unauthorized/reset-password.$token.tsx
  src/routes/_unauthorized/route.tsx
  src/services/api-client.ts
  src/shared/providers/ThemeProvider.tsx
  src/shared/ui/ant-provider-attributes.ts
  src/shared/ui/styles/global.scss
  src/shared/ui/styles/utils/_index.scss
  src/shared/ui/styles/utils/_mixins.scss
  src/shared/ui/styles/utils/_variables.scss
  src/shared/ui/themes/common.ts
  src/shared/ui/themes/dark.ts
  src/shared/ui/themes/light.ts
Labels: feature

#16 feat: create invite user flow, update login alerts, add some reusable…
  src/features/auth/api.ts
  src/features/auth/components/ForgotPasswordForm/ForgotPasswordForm.tsx
  src/features/auth/components/LoginForm/LoginForm.tsx
  src/features/auth/components/ResetPasswordForm/ResetPasswordForm.tsx
  src/features/auth/components/SignUpForm/SignUpForm.tsx
  src/features/auth/constants.ts
  src/features/auth/validation.ts
  src/features/session/types.ts
  src/features/users/api.ts
  src/features/users/components/InviteUserModal/InviteUserModal.tsx
  src/features/users/components/UserHeader.tsx
  src/features/users/components/UsersTable.tsx
  src/features/users/validation.ts
  src/routeTree.gen.ts
  src/routes/_unauthorized/index.module.scss
  src/routes/_unauthorized/login.tsx
  src/routes/_unauthorized/route.tsx
  src/routes/_unauthorized/sign-up.$token.tsx
  src/routes/index.tsx
  src/services/api-client.ts
  src/services/cookie-client.ts
  src/shared/providers/UserRoleProvider.tsx
  src/shared/ui/styles/utils/_mixins.scss
  src/shared/ui/styles/utils/_variables.scss
Labels: feature

#19 fix: access token expiration issues with logout
  src/features/session/api.ts
  src/services/api-client.ts
Labels: bug
